
    {name: 'App example with JWT Authentication', group: 'examples', link: 'https://github.com/Angarsk8/phoenix_vuejs_authentication_example'developed with [Phoenix Framework', group: 'examples', link: 'http://phoenixframework.org'}, , Vue and Vue Router ([_demo_', group: 'examples', link: 'https://phoenix-vue-auth.herokuapp.com)'by [@Angarsk8', group: 'examples', link: 'https://github.com/Angarsk8'}, 
    {name: 'Sample CRUD app with router in Vue 2.0', group: 'examples', link: 'https://github.com/shershen08/vue.js-v2-crud-application'by [@shershen08', group: 'examples', link: 'https://github.com/shershen08'}, 
    {name: 'ASP.NET Core Vue.js server-side rendering sample', group: 'examples', link: 'https://github.com/mgyongyosi/VuejsSSRSample'by [@mgyongyosi', group: 'examples', link: 'https://github.com/mgyongyosi'}, 
    {name: 'vuefire-quickstart', group: 'examples', link: 'https://github.com/sejr/vuefire-quickstart'- Documented Firebase integration w/ webpack and eslint, by [@sejr', group: 'examples', link: 'https://github.com/sejr'}, .
    {name: 'hello-vue-django Vue.js and Django integration starter project with hot code reload', group: 'examples', link: 'https://github.com/rokups/hello-vue-django'}, 
    {name: 'Real Time Social News App', group: 'examples', link: 'https://github.com/Angarsk8/loopa-news'developed with [Phoenix', group: 'examples', link: 'http://phoenixframework.org'}, , Vue, Vue Router and Vuex ([_demo_', group: 'examples', link: 'https://loopa-news.herokuapp.com)'by [@Angarsk8', group: 'examples', link: 'https://github.com/Angarsk8'}, 
    {name: 'vue-calculator', group: 'examples', link: 'https://github.com/CaiYiLiang/simply-calculator-vuejs'a simply calculator built with Vue 2.0, vue-cli(webpack-simple'}, . by [CaiYiLiang', group: 'examples', link: 'https://github.com/CaiYiLiang'}, 
    {name: 'Wikipedia-viewer', group: 'examples', link: 'https://github.com/CaiYiLiang/vue-demos/tree/master/wikipediaViewer-vuejs'A simple wikipedia-viewer page built with vue2.x ,vue-router,vue-cli(webpack-simple'and ajax(jsonp'}, . by [CaiYiLiang', group: 'examples', link: 'https://github.com/CaiYiLiang'}, 
    {name: 'vue2.x-douban', group: 'examples', link: 'https://github.com/superman66/vue2.x-douban'A simple of douban movie build with vue2.x,vue-router and axios(豆瓣电影'}, . by [Superman', group: 'examples', link: 'https://github.com/superman66'}, 
    {name: 'vue-laravel-example', group: 'examples', link: 'https://github.com/jcc/vue-laravel-example'Vue - Laravel - Example is a simple example to set Vue with Laravel. by [Jiajian Chan', group: 'examples', link: 'https://github.com/jcc'}, 
    {name: 'vue-foundation', group: 'examples', link: 'https://github.com/hal0gen/vue-foundation'A demo app integrating VueJS with [Zurb Foundation', group: 'examples', link: 'https://github.com/zurb/foundation-sites'}, , built using the webpack vue-cli template
    {name: 'aspnetcore-Vue-starter', group: 'examples', link: 'https://github.com/MarkPieszak/aspnetcore-Vue-starter'A VueJS 2 starter template as part of an asp.net MVC dotnetcore project. This template includes the VueJS client app and a backend API controller.
    {name: 'vue-reddit-app', group: 'examples', link: 'https://github.com/yujiahaol68/reddit-app'A Reddit SPA [_demo_', group: 'examples', link: 'https://yujiahaol68.github.io/reddit-app/'built with Vue 2.X , Vue Router 2 , Vuex and axios. Using Muse-UI and vue-cli webpack template by [@yujiahaol68', group: 'examples', link: 'https://github.com/yujiahaol68'}, 
    {name: 'vue-music-qq', group: 'examples', link: 'https://github.com/pluto1114/vue-music-qq'A qq-music project is based on vue-cli. The pages are simple and smooth
    {name: 'NavigationTab with Vue-Redux and Plain VueJSX', group: 'examples', link: 'https://github.com/ShuvoHabib/Vue-JSX-and-Vue-Redux-Navigation-Tab' Navigation Tab with both plain Vue JSX and Vue + Redux Binding
    {name: 'Veggie Map', group: 'examples', link: 'https://veggiemap.herokuapp.com/'An interactive demo using Vuejs + Vue router + Leaflet and Firebase
    {name: 'vuejs-d3', group: 'examples', link: 'https://github.com/johnnynotsolucky/samples/tree/master/vuejs-d3'examples how to use d3 for visualisations.
    {name: 'vue-twitter-client', group: 'examples', link: 'https://github.com/YuheiNakasaka/vue-twitter-client'A Twitter Client App build with Vue 2.X, Vuex, electron-vue and Electron
    {name: 'Douban', group: 'examples', link: 'https://github.com/jeneser/douban'Awesome douban Example created with Vue2.x + Vuex + Vue-router + vue-resource. by [jeneser', group: 'examples', link: 'https://github.com/jeneser'}, 
    {name: 'Storyblok vuejs-boilerplate', group: 'examples', link: 'https://github.com/storyblok/vuejs-boilerplate'- Integrates Storyblok's Component System, allows to create editable Websites.
    {name: 'Vuexpresso', group: 'examples', link: 'https://github.com/Ethaan/vuexpresso'- A boilerplate using VueX, Vue-Router, Vue-Apollo, webpack, GraphQL, Apollo-client, express and mongo
    {name: 'Vue.js with Sails.js backend example project', group: 'examples', link: 'https://github.com/ndabAP/Vue.js-with-Sails.js-backend-example-project'- This project is for those who are new to single-page applications and want to learn through a real example.
    {name: 'Vue.js & Pyramid web framework app', group: 'examples', link: 'https://github.com/eddyekofo94/pyramidVue.git'- A boilerplate using Pylons Pyramid webframework backend Vuejs webpack2, vue-router, yarn(packet manager'}, 
    {name: 'vue-feathers-chat', group: 'examples', link: 'https://github.com/ErickPetru/vue-feathers-chat'A sample realtime chat made with Vue in frontend and Feathers in backend, but using just Socket.IO-Client for the communication
    {name: 'vue-xplan', group: 'examples', link: 'https://github.com/JackGit/xplan/'A rotating earth demo page created with Vue and three.js
    {name: 'vueSocketChatRoom', group: 'examples', link: 'https://github.com/Chanran/vueSocketChatroom'A socket chat room using vue2.x,vuex2.x,vue-router2.x,vux2.x,socket.io
    {name: 'vue-tetris (Use Vue, Vuex, Immutable to code Tetris)', group: 'examples', link: 'http://binaryify.github.io/vue-tetris/'by [@Binaryify', group: 'examples', link: 'https://github.com/Binaryify'}, : Use Vue, Vuex, Immutable to code Tetris.
    {name: 'route-planner-vue', group: 'examples', link: 'https://kasheftin.github.io/route-planner-vue/'by [@Kasheftin', group: 'examples', link: 'https://github.com/Kasheftin'}, : The tool for planning routes with multiple sortable layers, draggable directions, markers and shapes on google map.
    {name: 'MyDiary-Vue', group: 'examples', link: 'https://github.com/ssshooter/MyDiary-Vue/blob/master/README.En.md'A diary application build with Vue 2.X which is also have contact and todolist function
    {name: 'VueJS Example Projects', group: 'examples', link: 'https://github.com/vue-project'on Github by [Ali GÖREN', group: 'examples', link: 'https://aligoren.com'}, 
    {name: 'todo-mvc-webpack', group: 'examples', link: 'https://github.com/voluntadpear/todomvc-vue-webpack'by [voluntapear', group: 'examples', link: 'https://github.com/voluntadpear'TodoMVC implementation on Vue 2 using the webpack-basic template with examples showing vuex, vue-router, central event bus and VueFire.
    {name: 'Chess Storybook Example', group: 'examples', link: 'https://github.com/gustaYo/vue-chess-storybook'with Vue 2.0 by [gustaYo', group: 'examples', link: 'https://github.com/gustaYo'}, 
    {name: 'Vue Weather Notifier', group: 'examples', link: 'https://github.com/sdras/vue-weather-notifier'A small sample animation app with SVG and Vuex
    {name: 'Nuxt Type', group: 'examples', link: 'https://github.com/sdras/nuxt-type'An example Vue project with Nuxt for routing/SSR to demo page transitions
    {name: 'VueBlog', group: 'examples', link: 'https://github.com/wmui/vueblog'A blog system supporting service side rendering by [wmui', group: 'examples', link: 'https://github.com/wmui'}, 
    {name: 'Cinemateka', group: 'examples', link: 'https://github.com/Piterden/cinemateka'- An example of SPA made with Vue v1 & Laravel 5. Film & events schedule. Russian comments.
    {name: 'vue-2.x-boilerplate', group: 'examples', link: 'https://github.com/the6thm0nth/vue-2.x-boilerplate'- A simple and small startker kit for a Vue project Vuex + vue-router
    {name: 'vue-minesweeper', group: 'examples', link: 'https://github.com/rhapsodyn/vue-minesweeper'- A deadly simple minesweeper game with vuejs by [rhapsodyn', group: 'examples', link: 'https://github.com/rhapsodyn'}, 
    {name: 'X-Flowchart-Vue', group: 'examples', link: 'https://github.com/OXOYO/X-Flowchart-Vue'- A flowchart editor with SVG and Vue by [OXOYO', group: 'examples', link: 'https://github.com/OXOYO'}, 
    {name: 'koa-vue-notes-web', group: 'examples', link: 'https://github.com/johndatserakis/koa-vue-notes-web'- A fleshed-out SPA using Koa 2.3 on the backend and Vue 2.4 on the frontend. Includes fully featured user-authentication components, CRUD actions for the user's notes, and Vuex store modules.
    {name: 'Vuejs Shopping Cart', group: 'examples', link: 'https://github.com/ittus/vuejs-firebase-shopping-cart'- Shopping cart example using Vuejs and Firebase
    {name: 'PokedexVueJs', group: 'examples', link: 'https://github.com/rchung95/PokedexVueJs'', author: '@ rchung95
    {name: 'vuefire-auth', group: 'examples', link: 'https://github.com/aofdev/vuefire-auth'A Vuefire Vue2-Auth-Email Verification with Firebase
    {name: 'vuefire-realtimedatabase', group: 'examples', link: 'https://github.com/aofdev/vuefire-realtimedatabase'A Vuefire Vue2-RealtimeDatabaseCRUD with Firebase
    {name: 'vuefire-storage', group: 'examples', link: 'https://github.com/aofdev/vuefire-storage'A Vuefire Vue2-Storage with Firebase
    {name: 'Vue2-PWA-Blog', group: 'examples', link: 'https://github.com/deepak-singh/vue-blog-pwa'', author: '@ deepak-singh
    {name: 'vue-firebase-auth-vuex', group: 'examples', link: 'https://github.com/aofdev/vue-firebase-auth-vuex'A Vue2 Firebase Authentication with Vuex and support Progressive Web Apps
