export default {
  name: 'items',
  items: [
    // #resources
    // - #official-resources
    {name: 'Official Guide', group: 'official-resources', link: 'http://vuejs.org/guide/'}, 
    {name: 'API Reference', group: 'official-resources', link: 'http://vuejs.org/api/'}, 
    {name: 'GitHub Repo', group: 'official-resources', link: 'https://github.com/vuejs/vue'}, 
    {name: 'Release Notes', group: 'official-resources', link: 'https://github.com/vuejs/vue/releases'}, 

    // - #external-resources    
    {name: 'Vue.js資料まとめ(for japanese)', group: 'external-resources', link: 'https://gist.github.com/hashrock/f575928d0e109ace9ad0', author: '@hashrock'},
    {name: 'Vue.js Newsletter', group: 'external-resources', link: 'http://vue-newsletter.com/', description: 'Weekly dose of handpicked Vue.js news'},
    {name: 'Vue.js Tips', group: 'external-resources', link: 'http://vuetips.com', description: 'Tips to become a better Vue.js developer'},
    {name: 'Vue.js Wikipedia', group: 'external-resources', link: 'https://en.wikipedia.org/wiki/Vue.js'},
    {name: 'Vue.js Radar', group: 'external-resources', link: 'https://www.vuejsradar.com', description: 'Curated newsletter + site covering new Vue.js releases/contributions.'},

    // #job-portal
    {name: 'Vue.js Jobs - VueJobs', group: 'job-portal', link: 'https://vuejobs.com/', description:  'A Vue.js job portal to hire or get hired for all your Vue.js jobs.'},
    
    // #community
    {name: 'Twitter', group: 'community', link: 'https://twitter.com/vuejs'}, 
    {name: 'Official Forum', group: 'community', link: 'http://forum.vuejs.org/'}, 
    {name: 'vue-requests', group: 'community', link: 'https://github.com/vuejs/vue-requests', description: 'Request a Vue.js module you wish existed or get ideas for modules'}, 
    {name: 'VueJS Iran - Telegram Channel & group (group link available in channel bio)', group: 'community', link: 'https://telegram.me/vue_js'}, 
    {name: 'vueslack - 1300+ registered users worldwide', group: 'community', link: 'https://vueslack.com/'}, 
    {name: 'Vue Land - Discord chat server', group: 'community', link: 'https://vue-land.js.org/'}, 
    {name: 'VueJS Russia - Telegram Group [Russian]', group: 'community', link: 'https://t.me/vuejs_ru'}, 
    {name: 'VueJS Viet Nam - Facebook group', group: 'community', link: 'https://www.facebook.com/groups/vuejsvietnam/'},
    {name: 'VueJS Spanish - Slack Group', group: 'community', link: 'https://slack.vue-es.org/'}, 
    {name: 'VueJS Korean - Slack Group', group: 'community', link: 'https://vuejs-korea.signup.team/'}, 
    {name: 'VueJS Thailand - Facebook Group', group: 'community', link: 'https://www.facebook.com/groups/VuejsThailand/'},
    {name: 'VueJS Brasil - Telegram Group [Portuguese]', group: 'community', link: 'https://t.me/vuejsbrasil'}, 
    {name: 'VueJS Brasil - Facebook Page [Portuguese]', group: 'community', link: 'https://www.facebook.com/vuejsbrasil/'}, 
    {name: 'VueJS Brasil - Facebook Group [Portuguese]', group: 'community', link: 'https://www.facebook.com/groups/vuejsbr/'}, 

    // #conference
    {name: 'VueConf', group: 'conferences', link: 'http://conf.vuejs.org'}, 
    {name: 'Vue.js London', group: 'conferences', link: 'http://vuejs.london'}, 

    // #podcasts
    {name: 'Full Stack Radio #30 (11-23-2015)', group: 'podcasts', link: 'http://www.fullstackradio.com/30'}, 
    {name: 'JavaScript Jabber #187 (11-25-2015)', group: 'podcasts', link: 'https://devchat.tv/js-jabber/187-jsj-vue-js-with-evan-you'}, 
    {name: 'Changelog #184 (11-27-2015)', group: 'podcasts', link: 'https://changelog.com/184/'}, 
    {name: 'Software Engineering Daily (12-29-2015)', group: 'podcasts', link: 'http://softwareengineeringdaily.com/2015/12/29/front-end-javascript-with-evan-you/'}, 
    {name: 'Javascript Air 016 (03-30-2016)', group: 'podcasts', link: 'https://javascriptair.com/episodes/2016-03-30/'}, 
    {name: 'Codecasts #2 - Falando Sobre Vuejs e Web Components (2016-08-19) [pt-BR]', group: 'podcasts', link: 'https://soundcloud.com/codecasts/2-falando-sobre-vuejs-e-web-components'}, 
    {name: 'Full Stack Radio #50 (09-21-2016)', group: 'podcasts', link: 'http://www.fullstackradio.com/50'}, 
    {name: '和 Vue.js 框架的作者聊聊前端框架开发背后的故事 [zh-CN]', group: 'podcasts', link: 'http://teahour.fm/2015/08/16/vuejs-creator-evan-you.html'}, 
    {name: 'MW S04E08 - Vue.js with Evan You and Sarah Drasner (04-27-2017)', group: 'podcasts', link: 'https://modernweb.podbean.com/e/mw-s04e09-evan-yu-sarah-drasner/'}, 
    {name: 'Request For Commits #12 - Crowdfunding Open Source (Vue.js) (06-15-2017)', group: 'podcasts', link: 'https://changelog.com/rfc/12'}, 
    {name: 'The Web Platform Podcast 132: Vue.js (07-27-2017)', group: 'podcasts', link: 'http://thewebplatformpodcast.com/132-vuejs'}, 
    {name: 'JavaScript Jabber #276 with Maximilian Schwarzmüller (08-29-2017)', group: 'podcasts', link: 'https://devchat.tv/js-jabber/jsj-276-vue-js-maximilian-schwarzmuller'}, 
  
    // #official-examples
    {name: 'Basic Examples', group: 'official-examples', link: 'http://vuejs.org/guide/'}, 
    {name: 'Vue.js TodoMVC', group: 'official-examples', link: 'https://github.com/vuejs/vue/tree/dev/examples/todomvc'}, 
    {name: 'CoffeeScript Version', group: 'official-examples', link: 'https://github.com/anfelor/TodoMVC-CoffeeScript-and-Vue.js'}, 
    {name: 'Vue.js HackerNews Clone', group: 'official-examples', link: 'https://github.com/vuejs/vue-hackernews'}, 
    {name: 'Vue.js 2.0 HackerNews Clone', group: 'official-examples', link: 'https://github.com/vuejs/vue-hackernews-2.0'}, 
    
    // #books
    {name: 'The Majesty Of Vue.js', group: 'books', link: 'https://www.packtpub.com/web-development/majesty-vuejs', author: 'Alex Kyriakidis & Kostas Maniatis, Packt. (Nov 2016'}, 
    {name: 'Learning Vue.js 2', group: 'books', link: 'https://www.packtpub.com/web-development/learning-vuejs-2', author: 'Olga Filipova, Packt. (Dec 2016'}, 
    {name: 'The Majesty Of Vue.js 2', group: 'books', link: 'https://leanpub.com/vuejs2', author: 'Alex Kyriakidis and Kostas Maniatis, Leanpub. (Mar 2017'}, 
    {name: 'Vue.js 2 Cookbook', group: 'books', link: 'https://www.packtpub.com/web-development/vuejs-2-cookbook', author: 'Andrea Passaglia, Packt. (May 2017'}, 
    {name: 'Vue.js in Action', group: 'books', link: 'https://www.manning.com/books/vue-js-in-action', author: 'Erik Hanchett and Benjamin Listwon (Spring 2018'}, 

    // #commercial-products
    {name: 'Wijmo', group: 'commercial-products', link: 'http://wijmo.com/products/wijmo-5/', description: 'A collection of UI controls with VueJS support.'}, 
    {name: 'Collate Notes', group: 'commercial-products', link: 'http://www.collatenotes.com/'}, 
    {name: 'Formester', group: 'commercial-products', link: 'https://www.formester.com/', description: 'Form, email marketing automation made easy'}, 
    {name: 'ChatWoot', group: 'commercial-products', link: 'https://www.chatwoot.com/', description: 'Livechat and agent collaboration over facebook messenger.'}, 

    // #tutorials
    {name: 'Vue.js screencasts', group: 'tutorials', link: 'https://laracasts.com/series/learn-vue-2-step-by-step', author: 'Laracasts'}, 
    {name: 'What\'s New in Vue.js 1.0', group: 'tutorials', link: 'http://www.sitepoint.com/whats-new-in-vue-js-1-0/', author: 'Sitepoint'}, 
    {name: 'Build an App with Vue.js: From Authentication to Calling an API', group: 'tutorials', link: 'https://auth0.com/blog/2015/11/13/build-an-app-with-vuejs/', author: 'Auth0 blog'}, 
    {name: 'Create a GitHub File Explorer Using Vue.js', group: 'tutorials', link: 'https://scotch.io/tutorials/create-a-github-file-explorer-using-vue-js', author: 'Scotch.io'}, 
    {name: 'Vue.js Tutorial', group: 'tutorials', link: 'http://vegibit.com/vue-js-tutorial/', author: 'Vegibit'},
    {name: 'Vue.js build set-up from scratch with webpack, vue-loader and hot reload', group: 'tutorials', link: 'http://skyronic.com/2015/12/28/vue-project-scratch/'}, 
    {name: 'Vuex basics: Tutorial and explanation', group: 'tutorials', link: 'http://skyronic.com/2016/01/03/vuex-basics-tutorial/'}, 
    {name: 'Vuex introduction video - James Browne from London Vue.js Meetup #1', group: 'tutorials', link: 'https://www.youtube.com/watch?v=l1KHL-TX3qs'}, 
    {name: 'Vue.js 中文系列视频教程', group: 'tutorials', link: 'https://laravist.com/series/vue-js-1-0-in-action-series', author: 'Laravist'}, 
    {name: 'Vue.js: The Basics', group: 'tutorials', link: 'http://coligo.io/vuejs-the-basics/', author: 'Coligo.io'}, 
    {name: 'VueJs: Components', group: 'tutorials', link: 'https://coligo.io/vuejs-components/', author: 'Coligo.io'}, 
    {name: 'Dynamic Components in Vue.js', group: 'tutorials', link: 'https://coligo.io/dynamic-components-in-vuejs/', author: 'Coligo.io'}, 
    {name: 'Develop a Reactive Invoice App using Vue.js', group: 'tutorials', link: 'http://craigmckenna.com/develop-a-reactive-invoice-app-using-vue-js/', author: 'craigmckenna.com'},
    {name: 'Understanding Filters in Vue.js', group: 'tutorials', link: 'http://coligo.io/vuejs-filters/', author: 'Coligo.io'}, 
    {name: 'Hybrid App Example with Laravel and Vue.js in Portuguese', group: 'tutorials', link: 'https://www.youtube.com/watch?v=TGSJjDahlrQ', author: 'vedovelli'},
    {name: 'Creating a Markdown Editor with VueJs and GitHub\'s API', group: 'tutorials', link: 'http://coligo.io/markdown-editor-vuejs/', author: 'Coligo.io'}, 
    {name: 'Building a Real-Time Web Analytics Dashboard with NodeJs, Socket.io, and VueJs', group: 'tutorials', link: 'http://coligo.io/real-time-analytics-with-nodejs-socketio-vuejs/', author: 'Coligo.io'}, 
    {name: 'Vue.js Introduction Turkish Language', group: 'tutorials', link: 'http://oguzhan.in/vue-js-ile-uygulama-gelistirme/', author: 'oguzhan.in'},
    {name: 'Vue.js VideoTutoral Series in Spanish (3-8-2016)', group: 'tutorials', link: 'https://www.youtube.com/watch?v=IlFk3cyRB0Y&list=PLM-Y_YQmMEqD2EWfWpSbiV3WgShRRW3FE&index=7', author: 'YouTube by Juan Andrés Núñez'},
    {name: 'Building a Bookmarking App with Electron, VueJs, and Firebase', group: 'tutorials', link: 'http://coligo.io/bookmarking-app-electron-vuejs-firebase/', author: 'Coligo.io'}, 
    {name: 'Learn Vuex by Building a Notes App', group: 'tutorials', link: 'https://coligo.io/learn-vuex-by-building-notes-app/', author: 'Coligo.io'}, 
    {name: 'Vue.js Screencast Series in Spanish', group: 'tutorials', link: 'https://styde.net/curso-de-vue-js/', author: 'Styde.net'},
    {name: '**讲解Vue.js 官网 中文-含代码、百度云、youtube**', group: 'tutorials', link: 'https://github.com/bhnddowinf/vuejs-learn', author: 'bhnddowinf'},
    {name: 'Exploring Real Time Apps with VueJS, ES2015 and Webpack', group: 'tutorials', link: 'https://blog.pusher.com/exploring-real-time-apps-with-vuejs-es2016-and-webpack/', author: 'Pusher'},
    {name: 'Vue.js in Bahasa Indonesia', group: 'tutorials', link: 'https://www.sekolahkoding.com/track/belajar-vue-js', author: 'sekolahkoding.com'},
    {name: 'Building a Mobile App with Cordova and Vue.js', group: 'tutorials', link: 'https://coligo.io/building-a-mobile-app-with-cordova-vuejs/', author: 'Coligo.io'}, 
    {name: 'Vue.js from Scratch Series in Russian', group: 'tutorials', link: 'https://www.youtube.com/playlist?list=PL5r0NkdgM0UOxb4Hl81FV5UIgexwTf8h7', author: 'YouTube by .dev'},
    {name: 'Створення сервісу для зберігання файлів з Flask, RethinkDB та Vue.js, ч. 1', group: 'tutorials', link: 'http://codeguida.com/post/526/'}, 
    {name: 'VueJS 2 French tutorial', group: 'tutorials', link: 'https://www.youtube.com/playlist?list=PLjwdMgw5TTLW-mAtlR46VajrKs4dep3y0'}, 
    {name: 'Jayway Vue.js 2 workshop. Build an e-commerce site with vue-router, vuex and vue-resource', group: 'tutorials', link: 'https://github.com/jayway/vue-js-workshop'}, 
    {name: 'How to Create Great VueJS Applications Using Wijmo Controls', group: 'tutorials', link: 'http://wijmo.com/blog/how-to-create-great-vuejs-applications-using-wijmo-controls/'}, 
    {name: '**讲解Vue.js 2 官网 中文-含代码、百度云、youtube**', group: 'tutorials', link: 'https://github.com/bhnddowinf/vuejs2-learn', author: 'bhnddowinf'},
    {name: 'Vue.js Cheatsheet: Server-side Applications, Router, Vuex Store, GraphQL and more', group: 'tutorials', link: 'https://www.gitbook.com/book/xpepermint/vue-js-cheatsheet/details', author: '@xpepermint'}, 
    {name: 'Medium like Image Loading with Vue.js', group: 'tutorials', link: 'https://www.theodo.fr/blog/2016/10/medium-like-image-loading-with-vue-js/'}, 
    {name: 'How to Use Vuex in a Laravel Spark Project', group: 'tutorials', link: 'https://metricloop.com/blog/how-to-use-vuex-in-a-laravel-spark-project', author: '[Metric Loop', group: 'tutorials', link: 'https://metricloop.com/blog'}, 
    {name: 'How To Set Up Modules in Vuex', group: 'tutorials', link: 'https://metricloop.com/blog/how-to-set-up-modules-in-vuex', author: '[Metric Loop', group: 'tutorials', link: 'https://metricloop.com/blog'}, 
    {name: 'Learn Vue 2: Step By Step', group: 'tutorials', link: 'https://laracasts.com/series/learn-vue-2-step-by-step', author: 'Laracasts'}, 
    {name: 'Vue.js 中文教程', group: 'tutorials', link: 'http://javascript.ctolib.com/docs/read/vue-js-c-index.html'}, 
    {name: 'Up and Running with the Vue.js 2.0 Framework', group: 'tutorials', link: 'https://www.sitepoint.com/up-and-running-vue-js-2-0/', author: 'Sitepoint'}, 
    {name: 'How to make API Calls with Vuex', group: 'tutorials', link: 'https://metricloop.com/blog/how-to-make-api-calls-with-vuex', author: '[Metric Loop', group: 'tutorials', link: 'https://metricloop.com/blog'}, 
    {name: 'How to Use Vuex to Build a Feature', group: 'tutorials', link: 'https://metricloop.com/blog/how-to-use-vuex-to-build-a-feature', author: '[Metric Loop', group: 'tutorials', link: 'https://metricloop.com/blog'}, 
    {name: 'Vue.js 2.0 Fundamentals', group: 'tutorials', link: 'https://www.youtube.com/playlist?list=PLwAKR305CRO_1yAao-8aZiQnBqJeyng4O', author: 'YouTube by DevMarketer'},
    {name: 'Vuex For The Clueless — The Missing Primer On Vue’s Application Data Store', group: 'tutorials', link: 'https://medium.com/js-dojo/vuex-for-the-clueless-the-missing-primer-on-vues-application-data-store-33fa51ffc3af#.2j25xpfui'}, 
    {name: 'Real-time Grid Component Laravel, Vue.js, Vuex & Socket.io', group: 'tutorials', link: 'https://www.youtube.com/watch?v=Jxefsv5Zqkw&t=3s'}, 
    {name: 'VueJS 2 - The Complete Guide (incl. Vuex)', group: 'tutorials', link: 'https://www.udemy.com/vuejs-2-the-complete-guide'}, 
    {name: 'Develop Web Apps with Vue.js', group: 'tutorials', link: 'https://egghead.io/courses/develop-web-apps-with-vue-js', author: '[egghead.io', group: 'tutorials', link: 'https://egghead.io/'}, 
    {name: 'Vue.js 2 - Getting Started', group: 'tutorials', link: 'https://www.youtube.com/playlist?list=PL55RiY5tL51p-YU-Uw90qQH419BM4Iz07'}, 
    {name: 'Vue.js 2 & Vuex (Basics)', group: 'tutorials', link: 'https://www.youtube.com/playlist?list=PL55RiY5tL51pT0DNJraU93FhMzhXxtDAo'}, 
    {name: 'Türkçe VueJS Eğitim Videoları', group: 'tutorials', link: 'https://www.youtube.com/playlist?list=PLa3NvhdFWNipwk1KXeUpVQnAiAfuBw4El', author: 'YouTube by Fatih Acet'}, 
    {name: 'Building a JSON Tree View Component in Vue.js from Scratch in Six Steps', group: 'tutorials', link: 'https://devblog.digimondo.io/building-a-json-tree-view-component-in-vue-js-from-scratch-in-six-steps-ce0c05c2fdd8#.738ok0l4p', author: '[digimondo devblog'}, 
    {name: 'Let\'s Vue! - OpenLecture 2017.01 in Russian', group: 'tutorials', link: 'https://youtu.be/7pmw5gvWAf8', author: 'YouTube by Illya Klymov ([@xanf', group: 'tutorials', link: 'https://github.com/xanf/'}, 
    {name: 'Bootstrapping your first Vue.js application using vue-cli', group: 'tutorials', link: 'https://afropolymath.svbtle.com/bootstrapping-your-first-vue-js-project/', author: '@afropolymath'}, 
    {name: 'Build vue-hackernews-2.0 from Scratch', group: 'tutorials', link: 'https://github.com/Detachment/Build-vue-hackernews-2.0-from-scratch', author: '@ Detachment'}, 
    {name: 'Role Based Authorization for your Vue.js and Nuxt.js Applications Using vue-kindergarten', group: 'tutorials', link: 'https://medium.com/@JiriChara/role-based-authorization-for-your-vue-js-and-nuxt-js-applications-using-vue-kindergarten-fd483e013ec5#.kp81np177'}, 
    {name: 'Complete Vue.js Application Tutorial - Creating a Simple Budgeting App with Vue', group: 'tutorials', link: 'http://matthiashager.com/complete-vuejs-application-tutorial', author: '@matthiaswh'}, 
    {name: 'Vue.js Tutorial: A Prerendered, SEO-Friendly Example', group: 'tutorials', link: 'https://snipcart.com/blog/vuejs-tutorial-seo-example'}, 
    {name: 'Vue.js Introduction For People Who Know Just Enough jQuery To Get By', group: 'tutorials', link: 'https://medium.com/@mattrothenberg/vue-js-introduction-for-people-who-know-just-enough-jquery-to-get-by-eab5aa193d77'}, 
    {name: 'Fetching Data from a Third-Party API with Vue.js and Axios', group: 'tutorials', link: 'https://www.sitepoint.com/fetching-data-third-party-api-vue-axios/'}, 
    {name: 'Fun Projects with Vue 2 (Video)', group: 'tutorials', link: 'https://www.packtpub.com/web-development/fun-projects-vue-2-video', author: 'Peter van Meijgaard, Packt. (April 2017)'}, 
    {name: 'Vue JS: Simultaneously Running Express and Webpack Dev Server', group: 'tutorials', link: 'https://medium.com/dailyjs/vue-js-simultaneously-running-express-and-webpack-dev-server-292f4a7ed7a3', author: 'Medium by Henrik Fogelberg'},
    {name: 'Vue JS 2 Tutorials', group: 'tutorials', link: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9gQcYgjhBoeQH7wiAyZNrYa', author: 'Youtube by The Net Ninja'}, 
    {name: 'Add a headless CMS to VueJs in 5 Minutes', group: 'tutorials', link: 'https://www.storyblok.com/tp/add-a-headless-CMS-to-vuejs-in-5-minutes'}, 
    {name: 'vue 架构中的 Watcher', group: 'tutorials', link: 'https://github.com/dengwanc/dengwanc.github.io/issues/11'}, 
    {name: 'Building Your First App With Vue.js', group: 'tutorials', link: 'http://tutorialzine.com/2016/08/building-your-first-app-with-vue-js/'}, 
    {name: '5 Practical Examples For Learning Vue.js', group: 'tutorials', link: 'http://tutorialzine.com/2016/03/5-practical-examples-for-learning-vue-js/'}, 
    {name: 'Migrating from KnockoutJS to VueJS', group: 'tutorials', link: 'https://jes.al/2017/05/migrating-from-knockoutjs-to-vuejs/', author: '@jesalg'}, 
    {name: 'Create a quiz with Vue.js', group: 'tutorials', link: 'https://medium.com/@rap2h/create-a-quiz-with-vue-js-ed1e8e0e8294', author: '@rap2h'}, 
    {name: 'Vue.js: Getting Started', group: 'tutorials', link: 'https://ecofic.com/courses/vue-getting-started/', author: '@chadcampbell'}, 
    {name: 'Vue.js 2 & Firebase - Building Real Time Single Page Web Applications', group: 'tutorials', link: 'https://www.youtube.com/watch?v=we4zuQIXmnw'}, 
    {name: 'Vue.js 2 & Vue-Resource - Real-World Application With External API Access', group: 'tutorials', link: 'https://www.youtube.com/watch?v=p-7Zi9xYt2M'}, 
    {name: 'Interactive Vue.js Screencasts For Beginners', group: 'tutorials', link: 'https://scrimba.com/playlist/playlist-38'}, 
    {name: 'Vue.JS ile NASA API\'ını Kullanarak Veri Çekme', group: 'tutorials', link: 'https://www.youtube.com/watch?v=uC5b2VDATDU', author: 'YouTube by [Ali GÖREN]'}, 
    {name: 'Web development with Vue.js 2 (Video)', group: 'tutorials', link: 'https://www.packtpub.com/web-development/web-development-vuejs-2-video', author: 'Olga Filipova, Packt. (June 2017)'}, 
    {name: 'Build a realtime chart with VueJS and Pusher', group: 'tutorials', link: 'https://blog.pusher.com/build-realtime-chart-with-vuejs-pusher/'}, 
    {name: 'Intro to Vue, repo for Frontend Masters Course', group: 'tutorials', link: 'https://github.com/sdras/intro-to-vue'}, 
    {name: 'Vue Guide on CSS-Tricks', group: 'tutorials', link: 'https://css-tricks.com/guides/vue/'}, 
    {name: 'Using Typescript in your VueJS app', group: 'tutorials', link: 'https://medium.com/coding-blocks/using-typescript-in-your-vue-app-c4aba0bbc8bc'}, 
    {name: 'Vue.js视频系列，免费、入门、实战', group: 'tutorials', link: 'http://nodelover.me/courses', author: 'nodelover'}, 
    {name: 'Vue.js 预览', group: 'tutorials', link: 'https://ninghao.net/course/4256', author: 'ninghao.net'}, 
    {name: 'Vue.js: Development Machine Setup', group: 'tutorials', link: 'https://www.ecofic.com/about/blog/vue-dev-machine-setup/', author: '@chadcampbell'}, 
    {name: 'Building a Vue v2 JS app using Vue-router', group: 'tutorials', link: 'https://www.liquidlight.co.uk/blog/article/building-a-vue-v2-js-app-using-vue-router/', author: '@mikestreety'}, 
    {name: 'Build your own carousel with Vue', group: 'tutorials', link: 'https://medium.com/@davidatomhernandez/how-to-a-simple-carousel-with-vue-138715d615d7', author: '@Atom_Hernandez'}, 
    {name: 'Unit Testing Vue.js Components with the Official Vue Testing Tools and Jest', group: 'tutorials', link: 'https://alexjoverm.github.io/series/Unit-Testing-Vue-js-Components-with-the-Official-Vue-Testing-Tools-and-Jest/', author: '@alexjoverm'}, 
    {name: 'Creating Vue.js Transitions & Animation: Live Examples', group: 'tutorials', link: 'https://snipcart.com/blog/vuejs-transitions-animations', author: '@udyuxdev'}, 
    {name: 'Creating Custom Vue.js Plugins] (https://alligator.io/vuejs/creating-custom-plugins/'}, 
    {name: 'Async in VueJS part 1', group: 'tutorials', link: 'https://medium.com/js-dojo/async-in-vue-js-part-1-28d96f751a2e'}, 
    {name: 'Async in VueJS part 2', group: 'tutorials', link: 'https://medium.com/js-dojo/async-in-vuejs-part-2-45e81c836e38'}, 

    // #examples    
    {name: 'Starter Application with JWT Auth + sample backend API in Laravel', group: 'examples', link: 'http://forum.vuejs.org/topic/39/starter-application-with-jwt-auth-sample-backend-api'}, 
    {name: 'Node Webkit + Vue example', group: 'examples', link: 'https://github.com/brandonjpierce/node-webkit-boilerplate', author: '@ brandonjpierce'},
    {name: 'Vue Samples', group: 'examples', link: 'https://github.com/superlloyd/VueSamples', author: '@ superlloyd'},
    {name: 'HackerNews clone with vue.js + vue-router', group: 'examples', link: 'https://github.com/kazupon/vue-router-hackernews', author: '@ kazupon'},
    {name: 'Electron + Vue example', group: 'examples', link: 'https://github.com/bradstewart/electron-boilerplate-vue', author: '@ bradstewart'},
    {name: 'Single page application example (Vue + Voie)', group: 'examples', link: 'https://github.com/inca/voie-example', author: 'Boris Okunskiy'}, 
    {name: 'Begin - Task Manager SPA written in Vue + Lumen', group: 'examples', link: 'https://github.com/rajabishek/begin', author: 'Raj Abishek'}, 
    {name: 'Vue Mini Shop', group: 'examples', link: 'https://github.com/BosNaufal/vue-mini-shop', author: 'BosNaufal'}, 
    {name: 'Vue SoundCloud', group: 'examples', link: 'https://github.com/mul14/vue-soundcloud', author: 'mul14'}, 
    {name: 'Feature Requests (Laravel + Vue Combo)', group: 'examples', link: 'https://github.com/haydenbbickerton/feature-requests-app', author: 'haydenbbickerton'}, 
    {name: 'Vue Cookbook (Vue1.0 + express)', group: 'examples', link: 'https://github.com/yjj5855/node-vue-server-webpack', author: '@yjj5855', description: 'A demo first screen rendering of a service'},
    {name: 'Strong Together', group: 'examples', link: 'https://github.com/websemantics/strong-together', description: 'A starter project to build single page Vue.js apps as stand-alone or for Laravel / Laravel Spark projects, based on Browserify and Semantic-ui', author: 'WebSemantics'}, 
    {name: 'vuetest: an ad admin web with user auth, bootstrap ui, uploader, WYSIWYG editor in iframe', group: 'examples', link: 'https://github.com/sjerrys/vuetest'}, 
    {name: 'vue-shopping', group: 'examples', link: 'https://github.com/andylei18/vue-shopping', author: 'andylei18'}, 
    {name: 'Vue-cnodejs,060', group: 'examples', link: 'https://github.com/shinygang/Vue-cnodejs', author: 'shinygang'}, 
    {name: 'vue-zhihu-daily', group: 'examples', link: 'https://github.com/hilongjw/vue-zhihu-daily', author: 'hilongjw'}, 
    {name: 'jwt-example', group: 'examples', link: 'https://github.com/PetervMeijgaard/jwt-example', author: 'petervmeijgaard'}, 
    {name: 'VueChess', group: 'examples', link: 'https://github.com/gustaYo/vue-chess', description: 'Multiplayer online chess game', author: 'gustaYo'}, 
    {name: 'Ngexplorer-vuejs-client', group: 'examples', link: 'https://github.com/gustaYo/ngexplorer-vuejs-client', author: 'Vue client for [Ngexplorer]', author: 'gustaYo'}, 
    {name: 'Vue 2048 (Vue + Webpack)', group: 'examples', link: 'https://pengfu.github.io/vue-2048/', author: '@pengfu', description: 'Popular 2048-Game implemented using Vue,Webpack,Sass,ES6'}, 
    {name: 'Vue Simple PWA', group: 'examples', link: 'https://github.com/BosNaufal/vue-simple-pwa', author: 'BosNaufal'}, 
    {name: 'Tour of Heroes (Vue 2.0)', group: 'examples', link: 'https://github.com/aweber1/tour-of-heroes-vue2', description: 'A Vue 2.0 port of the Angular 2.0 [Tour of Heroes] demo app. Highlights: ES6/7, render functions, JSX, revue, vue-router, Airbnb eslint, webpack', author: '@aweber1'}, 
    {name: 'vue-table-pagination', group: 'examples', link: 'https://github.com/echoVic/vue-table-pagination', description: 'A table with pagination', author: 'echovic'}, 
    {name: 'Feathers and Vue 2.0 Blog Admin Demo', group: 'examples', link: 'https://github.com/delay/feathers-vue-blog-admin-demo', description: 'Demo for using Feathers with Vue 2.0. It includes authentication, vue-router, vue-infinite-loading and roles', author: 'delay'}, 
    {name: 'vue-zhihudaily-2.0', group: 'examples', link: 'https://github.com/cs1707/vue-zhihudaily-2.0', description: 'Zhihudaily demo built with Vue 2.0, vue-router & vuex, with server-side rendering', author: 'cs1707'}, 
    {name: 'vue-demo-todolist', group: 'examples', link: 'https://github.com/fishenal/Todos_Vuejs', description: 'a simply vue2.0 demo built with Vue 2.0, vue-cli', author: 'fishenal'}, 
    {name: 'vue-AdminLte', group: 'examples', link: 'https://github.com/liujians/vue-adminLte-vue-router', author: 'liujians'}, 
    {name: 'Vue(2.0)+ Node.js: A blog content manage system (CMS)', group: 'examples', link: 'https://github.com/ycwalker/CMS-of-Blog', author: '@ ycwalker'},
    {name: 'ngexplorer-quasar', group: 'examples', link: 'https://github.com/gustaYo/ngexplorer-quasar', description: 'Implementation of Ngexplorer with quasar framework', author: 'gustaYo'}, 
    {name: 'zhihu-daily-vue', group: 'examples', link: 'https://github.com/moonou/zhihu-daily-vue', description: 'a zhihu daily base on vue2.0', author: 'moonou'}, 
    {name: 'loopback-vue', group: 'examples', link: 'https://github.com/qxl1231/generator-loopback-vue', description: 'loopback+vue+vue-resource,ionic-app,vue page分页功能,authenticate 权限控制,accesstoken机制,credentials,CI,docker', author: 'qxl1231'}, 
    {name: 'vue-s3-dropzone', group: 'examples', link: 'https://github.com/kfei/vue-s3-dropzone', description: 'A Vue.js drag-and-drop component uploads files to AWS S3 serverlessly'}, 
    {name: 'easy-vue', group: 'examples', link: 'https://github.com/TIGERB/easy-vue', description: 'a easy example using the vue to implement easy web with vue 2.0', author: 'TIGERB'}, 
    {name: 'Vuex Events Messaging Demo', group: 'examples', link: 'https://github.com/metricloop/vuex-events-messaging-demo', author: 'Metric Loop'}, 
    {name: 'vue-memo', group: 'examples', link: 'https://github.com/akifo/vue-memo', description: 'a simple demo build with Vue.js(>2.x.)', author: 'akifo'}, 
    {name: 'Resume Vue', group: 'examples', link: 'https://github.com/ChangJoo-Park/Resume-Vue', description: 'JSON based Resume based on Vue 2.0', author: 'ChangJoo Park'}, 
  ]
}
